[project]
name = "pdf-splitter"
version = "0.1.0"
description = "A command-line utility for splitting PDF files"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["click", "rich", "PyPDF2"]

[project.scripts]
pdf-splitter = "pdf_splitter.cli:main"
